[package]
name = "milvue_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.17", features = ["multipart"] }
tokio = { version = "1.27.0", features = ["full"] }